version: 2

jobs:
  python:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user --requirement requirements.txt --requirement test_requirements.txt
      - run: python setup.py lint
      - run: ls -al
      - run: python setup.py test
  node:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test:node
  c++:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test:c++
workflows:
  version: 2
  build_and_test:
    jobs:
      - python
      - node
      - c++
