version: 2

jobs:
  python:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user --requirement requirements.txt --requirement test_requirements.txt
      - run: python setup.py lint
      - run: rm __init__.py
      - run: python setup.py test

  node:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test:node
      - run: bash <(curl -s https://codecov.io/bash)

  c++:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test:c++

  go:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go test ./... --cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - python
      - node
      - c++
      - go
